// ============================================================================
// HRMS Enterprise Solution - Comprehensive Seed Data (M01 to M20)
// ============================================================================

import type {
  CompanyProfile,
  Subsidiary,
  OrgUnit,
  WorkLocation,
  Employee,
  RoleDefinition,
  ApprovalChain,
  ServiceRequest,
  LeaveTypePolicy,
  EmployeeLeaveBalance,
  ShiftDefinition,
  ScheduleAssignment,
  DailyAttendanceRecord,
  PayrollGroup,
  PayrollRun,
  EmployeePayrollDetail,
  LoanRecord,
  FinalSettlementRecord,
  ExpenseCategory,
  ExpenseClaim,
  ExpenseReport,
  PerformanceCycle,
  EvaluationRecord,
  WorkforcePlan,
  JobOpening,
  Candidate,
  JobOffer,
  HardwareAsset,
  CompanyDocument,
  AuditLogEntry,
  AppNotification,
  AccountingJournalEntry,
} from "../../types";

// ----------------------------------------------------------------------------
// M02: Organization & Work Structure
// ----------------------------------------------------------------------------
export const mockCompany: CompanyProfile = {
  id: "comp-01",
  legalNameAr: "شركة فوكس القابضة لحلول التقنية وإدارة الأعمال",
  legalNameEn: "Focus Holding Enterprise Solutions Co.",
  taxNumber: "300123456700003",
  crNumber: "1010789654",
  country: "المملكة العربية السعودية",
  currency: "SAR",
  timezone: "Asia/Riyadh",
  headquartersAddress: "طريق الملك فهد، برج الفيصلية، الرياض 11564",
  fiscalYearStartMonth: 1,
};

export const mockSubsidiaries: Subsidiary[] = [
  {
    id: "sub-01",
    companyId: "comp-01",
    nameAr: "فوكس للتقنية وتطوير البرمجيات",
    nameEn: "Focus Software & Tech",
    code: "FOC-TECH",
    managerEmployeeId: "emp-01",
    managerName: "م. خالد المهيري",
    status: "active",
    employeeCount: 48,
    crNumber: "1010998877",
  },
  {
    id: "sub-02",
    companyId: "comp-01",
    nameAr: "فوكس للخدمات المالية والاستشارات",
    nameEn: "Focus Financial Services",
    code: "FOC-FIN",
    managerEmployeeId: "emp-02",
    managerName: "أ. نورة القحطاني",
    status: "active",
    employeeCount: 32,
    crNumber: "1010887766",
  },
  {
    id: "sub-03",
    companyId: "comp-01",
    nameAr: "فوكس للعمليات اللوجستية",
    nameEn: "Focus Logistics & Ops",
    code: "FOC-LOG",
    managerEmployeeId: "emp-03",
    managerName: "أ. فيصل الزهراني",
    status: "active",
    employeeCount: 65,
    crNumber: "1010776655",
  },
];

export const mockOrgUnits: OrgUnit[] = [
  {
    id: "org-tech",
    companyId: "comp-01",
    nameAr: "قطاع هندسة البرمجيات والتقنية",
    nameEn: "Software Engineering & Tech",
    code: "TECH-DIV",
    type: "division",
    managerEmployeeId: "emp-01",
    managerName: "م. خالد المهيري",
    status: "active",
    employeeCount: 48,
  },
  {
    id: "org-hr",
    companyId: "comp-01",
    nameAr: "الإدارة العامة للموارد البشرية",
    nameEn: "Human Resources Directorate",
    code: "HR-DIR",
    type: "division",
    managerEmployeeId: "emp-04",
    managerName: "أ. سارة العتيبي",
    status: "active",
    employeeCount: 14,
  },
  {
    id: "org-fin",
    companyId: "comp-01",
    nameAr: "الإدارة المالية والمحاسبة",
    nameEn: "Finance & Accounting Department",
    code: "FIN-DEPT",
    type: "department",
    managerEmployeeId: "emp-02",
    managerName: "أ. نورة القحطاني",
    status: "active",
    employeeCount: 18,
  },
  {
    id: "org-sales",
    companyId: "comp-01",
    nameAr: "إدارة المبيعات وتطوير الأعمال",
    nameEn: "Sales & Business Development",
    code: "SLS-DEPT",
    type: "department",
    managerEmployeeId: "emp-06",
    managerName: "أ. عبدالله الحربي",
    status: "active",
    employeeCount: 26,
  },
  {
    id: "org-ops",
    companyId: "comp-01",
    nameAr: "إدارة العمليات والمشاريع",
    nameEn: "Operations & Project Management",
    code: "OPS-DEPT",
    type: "department",
    managerEmployeeId: "emp-03",
    managerName: "أ. فيصل الزهراني",
    status: "active",
    employeeCount: 39,
  },
];

export const mockWorkLocations: WorkLocation[] = [
  {
    id: "loc-01",
    companyId: "comp-01",
    nameAr: "المقر الرئيسي - برج العليا (الرياض)",
    nameEn: "Headquarters - Olaya Tower (Riyadh)",
    code: "RUH-HQ",
    address: "شارع التحلية مع العليا، الرياض",
    latitude: 24.7015,
    longitude: 46.6744,
    radiusMeters: 150,
    status: "active",
    defaultShiftId: "shift-morning",
  },
  {
    id: "loc-02",
    companyId: "comp-01",
    nameAr: "فرع المنطقة الغربية - طريق الملك (جدة)",
    nameEn: "Western Hub - King Road (Jeddah)",
    code: "JED-HUB",
    address: "طريق الملك عبدالعزيز، الشاطئ، جدة",
    latitude: 21.5794,
    longitude: 39.1308,
    radiusMeters: 200,
    status: "active",
    defaultShiftId: "shift-morning",
  },
  {
    id: "loc-03",
    companyId: "comp-01",
    nameAr: "فرع المنطقة الشرقية - الكورنيش (الخبر)",
    nameEn: "Eastern Hub - Corniche (Khobar)",
    code: "KHB-HUB",
    address: "طريق الأمير تركي، الكورنيش، الخبر",
    latitude: 26.2886,
    longitude: 50.2185,
    radiusMeters: 180,
    status: "active",
    defaultShiftId: "shift-morning",
  },
];

// ----------------------------------------------------------------------------
// M03: Employees Master Records (Unified 360°)
// ----------------------------------------------------------------------------
export const mockEmployees: Employee[] = [
  {
    id: "emp-01",
    employeeNo: "FOC-0101",
    firstNameAr: "خالد",
    lastNameAr: "المهيري",
    firstNameEn: "Khalid",
    lastNameEn: "Al-Muhairi",
    email: "khalid.m@focus-hrms.com",
    personalEmail: "khalid.personal@example.com",
    phone: "+966 55 100 0101",
    nationalIdOrIqama: "1087654321",
    nationalIdExpiry: "2030-05-15",
    passportNo: "KSA-99881122",
    passportExpiry: "2029-11-20",
    nationality: "سعودي",
    gender: "male",
    birthDate: "1989-04-12",
    maritalStatus: "married",
    bloodType: "O+",
    dependentsCount: 3,
    avatarUrl:
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    subsidiaryId: "sub-01",
    subsidiaryName: "فوكس للتقنية وتطوير البرمجيات",
    departmentId: "org-tech",
    departmentName: "قطاع هندسة البرمجيات والتقنية",
    jobTitleAr: "رئيس قسم الهندسة البرمجية",
    jobTitleEn: "Lead Software Architect",
    jobGrade: "L5 - مدير تنفيذي أول",
    costCenter: "CC-101 - تقنية المعلومات",
    workType: "hybrid",
    managerId: null,
    workLocationId: "loc-01",
    workLocationName: "المقر الرئيسي - برج العليا (الرياض)",
    hireDate: "2021-03-01",
    contractStartDate: "2021-03-01",
    contractEndDate: "2027-03-01",
    qiwaContractNo: "QIWA-2021-99812",
    yearsOfService: 5,
    contractType: "full_time",
    status: "active",
    completionScore: 100,
    basicSalary: 18500,
    housingAllowance: 4625,
    transportAllowance: 1375,
    otherAllowances: 0,
    totalSalary: 24500,
    bankName: "مصرف الراجحي (Al Rajhi Bank)",
    iban: "SA44 8000 0201 6080 1000 1234",
    gosiNumber: "7788990011",
    gosiEmployeeDeduction: 1803.75,
    gosiEmployerContribution: 2173.75,
    nationalAddress: {
      buildingNo: "7214",
      street: "شارع التخصصي",
      district: "حي النخيل",
      city: "الرياض",
      postalCode: "12383",
      additionalNo: "3310",
    },
    emergencyContact: {
      name: "سعود المهيري",
      relation: "شقيق",
      phone: "+966 50 111 2233",
    },
    educationDegree: "ماجستير في هندسة البرمجيات والنظم السحابية",
    university: "جامعة الملك فهد للبترول والمعادن (KFUPM)",
    graduationYear: 2013,
    certifications: ["AWS Certified Solutions Architect - Professional", "TOGAF 9.2 Certified", "Scrum Alliance CSP"],
    languages: ["العربية (اللغة الأم)", "الإنجليزية (طلاقة احترافية كاملة)"],
    assignedAssets: [
      { name: "MacBook Pro M3 Max 16-inch", type: "كمبيوتر محمول", serialNo: "APL-M3-99882", assignedDate: "2023-11-10" },
      { name: "شاشة Dell UltraSharp 4K 27-inch", type: "شاشة مكتبية", serialNo: "DEL-4K-55410", assignedDate: "2023-11-10" },
      { name: "شريحة بيانات اتصالات 5G أعمال", type: "اتصالات", serialNo: "STC-5G-8812", assignedDate: "2021-03-01" },
    ],
    documentsList: [
      { type: "national_id", title: "الهوية الوطنية السعودية", docNo: "1087654321", expiryDate: "2030-05-15", status: "valid" },
      { type: "contract", title: "عقد العمل الموحد (قوى)", docNo: "QIWA-2021-99812", expiryDate: "2027-03-01", status: "valid" },
      { type: "degree", title: "شهادة الماجستير الأكاديمية", docNo: "KFUPM-MS-2013", expiryDate: "2099-01-01", status: "valid" },
      { type: "gosi", title: "شهادة الأجور والتأمينات", docNo: "GOSI-7788990011", expiryDate: "2026-12-31", status: "valid" },
    ],
  },
  {
    id: "emp-02",
    employeeNo: "FOC-0102",
    firstNameAr: "نورة",
    lastNameAr: "القحطاني",
    firstNameEn: "Noura",
    lastNameEn: "Al-Qahtani",
    email: "noura.q@focus-hrms.com",
    personalEmail: "noura.personal@example.com",
    phone: "+966 55 200 0102",
    nationalIdOrIqama: "1098765432",
    nationalIdExpiry: "2031-08-10",
    passportNo: "KSA-77665544",
    passportExpiry: "2028-04-15",
    nationality: "سعودية",
    gender: "female",
    birthDate: "1992-08-23",
    maritalStatus: "single",
    bloodType: "A+",
    dependentsCount: 0,
    avatarUrl:
      "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    subsidiaryId: "sub-02",
    subsidiaryName: "فوكس للخدمات المالية",
    departmentId: "org-fin",
    departmentName: "الإدارة المالية والمحاسبة",
    jobTitleAr: "مديرة الحسابات والرواتب",
    jobTitleEn: "Senior Payroll & Finance Manager",
    jobGrade: "L5 - مدير إدارة",
    costCenter: "CC-201 - الشؤون المالية",
    workType: "on_site",
    managerId: null,
    workLocationId: "loc-01",
    workLocationName: "المقر الرئيسي - برج العليا (الرياض)",
    hireDate: "2020-09-15",
    contractStartDate: "2020-09-15",
    contractEndDate: "2026-09-15",
    qiwaContractNo: "QIWA-2020-44120",
    yearsOfService: 6,
    contractType: "full_time",
    status: "active",
    completionScore: 98,
    basicSalary: 22000,
    housingAllowance: 5500,
    transportAllowance: 1500,
    otherAllowances: 0,
    totalSalary: 29000,
    bankName: "البنك الأهلي السعودي (SNB)",
    iban: "SA12 1000 0001 2345 6789 0001",
    gosiNumber: "6655443322",
    gosiEmployeeDeduction: 2145.0,
    gosiEmployerContribution: 2585.0,
    nationalAddress: {
      buildingNo: "3108",
      street: "طريق الملك عبدالعزيز",
      district: "حي الورود",
      city: "الرياض",
      postalCode: "12254",
      additionalNo: "4190",
    },
    emergencyContact: {
      name: "منيرة القحطاني",
      relation: "والدة",
      phone: "+966 50 333 4455",
    },
    educationDegree: "بكالوريوس في المحاسبة والعلوم المالية مع مرتبة الشرف",
    university: "جامعة الملك سعود (KSU)",
    graduationYear: 2014,
    certifications: ["SOCPA - زمالة الهيئة السعودية للمحاسبين", "CMA - محاسب إداري معتمد", "WPS Certification"],
    languages: ["العربية (اللغة الأم)", "الإنجليزية (ممتاز)"],
    assignedAssets: [
      { name: "Lenovo ThinkPad X1 Carbon Gen 11", type: "كمبيوتر محمول", serialNo: "LNV-X1-44321", assignedDate: "2023-01-15" },
      { name: "شاشة HP 24-inch FHD", type: "شاشة مكتبية", serialNo: "HP-24F-88190", assignedDate: "2020-09-15" },
    ],
    documentsList: [
      { type: "national_id", title: "الهوية الوطنية السعودية", docNo: "1098765432", expiryDate: "2031-08-10", status: "valid" },
      { type: "contract", title: "عقد العمل المالي", docNo: "QIWA-2020-44120", expiryDate: "2026-09-15", status: "valid" },
      { type: "degree", title: "شهادة البكالوريوس", docNo: "KSU-ACC-2014", expiryDate: "2099-01-01", status: "valid" },
    ],
  },
  {
    id: "emp-03",
    employeeNo: "FOC-0103",
    firstNameAr: "فيصل",
    lastNameAr: "الزهراني",
    firstNameEn: "Faisal",
    lastNameEn: "Al-Zahrani",
    email: "faisal.z@focus-hrms.com",
    personalEmail: "faisal.personal@example.com",
    phone: "+966 55 300 0103",
    nationalIdOrIqama: "1076543210",
    nationalIdExpiry: "2029-01-20",
    passportNo: "KSA-33221199",
    passportExpiry: "2028-10-10",
    nationality: "سعودي",
    gender: "male",
    birthDate: "1987-11-05",
    maritalStatus: "married",
    bloodType: "B+",
    dependentsCount: 4,
    avatarUrl:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    subsidiaryId: "sub-03",
    subsidiaryName: "فوكس للعمليات اللوجستية",
    departmentId: "org-ops",
    departmentName: "إدارة العمليات والمشاريع",
    jobTitleAr: "مدير عام العمليات",
    jobTitleEn: "Director of Operations",
    jobGrade: "L6 - مدير عام قطاع",
    costCenter: "CC-301 - العمليات اللوجستية",
    workType: "on_site",
    managerId: null,
    workLocationId: "loc-02",
    workLocationName: "فرع المنطقة الغربية - طريق الملك (جدة)",
    hireDate: "2022-01-10",
    contractStartDate: "2022-01-10",
    contractEndDate: "2028-01-10",
    qiwaContractNo: "QIWA-2022-55091",
    yearsOfService: 4,
    contractType: "full_time",
    status: "active",
    completionScore: 92,
    basicSalary: 24000,
    housingAllowance: 6000,
    transportAllowance: 1500,
    otherAllowances: 0,
    totalSalary: 31500,
    bankName: "بنك الرياض (Riyad Bank)",
    iban: "SA65 2000 0001 9876 5432 0003",
    gosiNumber: "5544332211",
    gosiEmployeeDeduction: 2340.0,
    gosiEmployerContribution: 2820.0,
    nationalAddress: {
      buildingNo: "8890",
      street: "طريق الكورنيش",
      district: "حي الشاطئ",
      city: "جدة",
      postalCode: "23412",
      additionalNo: "1190",
    },
    emergencyContact: {
      name: "حسام الزهراني",
      relation: "أخ",
      phone: "+966 54 888 9900",
    },
    educationDegree: "ماجستير في إدارة سلاسل الإمداد واللوجستيات",
    university: "جامعة الملك عبدالعزيز (KAU)",
    graduationYear: 2011,
    certifications: ["PMP - محترف إدارة المشاريع", "Lean Six Sigma Black Belt", "CSCP - Supply Chain Professional"],
    languages: ["العربية (اللغة الأم)", "الإنجليزية (ممتاز)"],
    assignedAssets: [
      { name: "Dell Latitude 7440", type: "كمبيوتر محمول", serialNo: "DEL-LAT-8819", assignedDate: "2022-01-10" },
      { name: "سيارة شركة تويوتا كامري 2024", type: "سيارة عهدة", serialNo: "CAR-KSA-9901", assignedDate: "2024-02-01" },
    ],
    documentsList: [
      { type: "national_id", title: "الهوية الوطنية السعودية", docNo: "1076543210", expiryDate: "2029-01-20", status: "valid" },
      { type: "contract", title: "عقد العمل القياسي", docNo: "QIWA-2022-55091", expiryDate: "2028-01-10", status: "valid" },
    ],
  },
  {
    id: "emp-04",
    employeeNo: "FOC-0104",
    firstNameAr: "سارة",
    lastNameAr: "العتيبي",
    firstNameEn: "Sara",
    lastNameEn: "Al-Otaibi",
    email: "sara.o@focus-hrms.com",
    personalEmail: "sara.personal@example.com",
    phone: "+966 55 400 0104",
    nationalIdOrIqama: "1065432109",
    nationalIdExpiry: "2032-11-01",
    passportNo: "KSA-55443311",
    passportExpiry: "2030-07-22",
    nationality: "سعودية",
    gender: "female",
    birthDate: "1990-02-18",
    maritalStatus: "married",
    bloodType: "AB+",
    dependentsCount: 2,
    avatarUrl:
      "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
    subsidiaryId: "sub-01",
    subsidiaryName: "فوكس للتقنية",
    departmentId: "org-hr",
    departmentName: "الإدارة العامة للموارد البشرية",
    jobTitleAr: "مديرة الموارد البشرية والعمليات",
    jobTitleEn: "Head of Human Resources",
    jobGrade: "L6 - مدير عام قطاع",
    costCenter: "CC-401 - الموارد البشرية",
    workType: "on_site",
    managerId: null,
    workLocationId: "loc-01",
    workLocationName: "المقر الرئيسي - برج العليا (الرياض)",
    hireDate: "2019-06-20",
    contractStartDate: "2019-06-20",
    contractEndDate: "2027-06-20",
    qiwaContractNo: "QIWA-2019-11002",
    yearsOfService: 7,
    contractType: "full_time",
    status: "active",
    completionScore: 100,
    basicSalary: 21500,
    housingAllowance: 5375,
    transportAllowance: 1625,
    otherAllowances: 0,
    totalSalary: 28500,
    bankName: "مصرف الإنماء (Alinma Bank)",
    iban: "SA05 0500 0001 3456 7890 0004",
    gosiNumber: "4433221100",
    gosiEmployeeDeduction: 2096.25,
    gosiEmployerContribution: 2526.25,
    nationalAddress: {
      buildingNo: "4401",
      street: "شارع العروبة",
      district: "حي المعذر",
      city: "الرياض",
      postalCode: "12331",
      additionalNo: "8821",
    },
    emergencyContact: {
      name: "سلطان العتيبي",
      relation: "زوج",
      phone: "+966 50 444 5566",
    },
    educationDegree: "ماجستير إدارة الموارد البشرية الاستراتيجية",
    university: "جامعة الملك سعود بالتعاون مع CIPD",
    graduationYear: 2015,
    certifications: ["SHRM-SCP - Senior Certified Professional", "CIPD Level 7 Diploma", "مستشار موارد بشرية معتمد"],
    languages: ["العربية (اللغة الأم)", "الإنجليزية (طلاقة كاملة)"],
    assignedAssets: [
      { name: "Apple MacBook Air M2 15-inch", type: "كمبيوتر محمول", serialNo: "APL-AIR-7712", assignedDate: "2023-04-10" },
      { name: "آيباد برو 12.9 M2", type: "جهاز لوحي", serialNo: "APL-IPD-3301", assignedDate: "2023-04-10" },
    ],
    documentsList: [
      { type: "national_id", title: "الهوية الوطنية السعودية", docNo: "1065432109", expiryDate: "2032-11-01", status: "valid" },
      { type: "contract", title: "عقد العمل الموحد", docNo: "QIWA-2019-11002", expiryDate: "2027-06-20", status: "valid" },
      { type: "degree", title: "شهادة الماجستير", docNo: "KSU-HR-2015", expiryDate: "2099-01-01", status: "valid" },
    ],
  },
  {
    id: "emp-05",
    employeeNo: "FOC-0105",
    firstNameAr: "محمد",
    lastNameAr: "الشمري",
    firstNameEn: "Mohammed",
    lastNameEn: "Al-Shammari",
    email: "mohammed.s@focus-hrms.com",
    personalEmail: "mohammed.personal@example.com",
    phone: "+966 55 500 0105",
    nationalIdOrIqama: "1054321098",
    nationalIdExpiry: "2033-03-25",
    passportNo: "KSA-11998877",
    passportExpiry: "2029-08-18",
    nationality: "سعودي",
    gender: "male",
    birthDate: "1995-07-30",
    maritalStatus: "single",
    bloodType: "O-",
    dependentsCount: 0,
    avatarUrl:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    subsidiaryId: "sub-01",
    subsidiaryName: "فوكس للتقنية",
    departmentId: "org-tech",
    departmentName: "قطاع هندسة البرمجيات والتقنية",
    jobTitleAr: "مطور واجهات أمامية أول",
    jobTitleEn: "Senior Frontend Engineer",
    jobGrade: "L3 - اختصاصي أول",
    costCenter: "CC-101 - تقنية المعلومات",
    workType: "remote",
    managerId: "emp-01",
    managerName: "خالد المهيري",
    workLocationId: "loc-01",
    workLocationName: "المقر الرئيسي - برج العليا (الرياض)",
    hireDate: "2023-02-05",
    contractStartDate: "2023-02-05",
    contractEndDate: "2027-02-05",
    qiwaContractNo: "QIWA-2023-88901",
    yearsOfService: 3,
    contractType: "full_time",
    status: "active",
    completionScore: 88,
    basicSalary: 14500,
    housingAllowance: 3625,
    transportAllowance: 875,
    otherAllowances: 0,
    totalSalary: 19000,
    bankName: "البنك السعودي الفرنسي (BSF)",
    iban: "SA44 5500 0001 8877 6655 0005",
    gosiNumber: "3322110099",
    gosiEmployeeDeduction: 1413.75,
    gosiEmployerContribution: 1703.75,
    nationalAddress: {
      buildingNo: "2190",
      street: "شارع الإمام سعود بن فيصل",
      district: "حي الصحافة",
      city: "الرياض",
      postalCode: "13321",
      additionalNo: "5501",
    },
    emergencyContact: {
      name: "فهد الشمري",
      relation: "أب",
      phone: "+966 50 555 6677",
    },
    educationDegree: "بكالوريوس علوم الحاسب والمعلومات",
    university: "جامعة الإمام محمد بن سعود الإسلامية",
    graduationYear: 2018,
    certifications: ["Meta Frontend Developer Professional", "AWS Certified Developer - Associate"],
    languages: ["العربية (اللغة الأم)", "الإنجليزية (جيد جداً)"],
    assignedAssets: [
      { name: "MacBook Pro M2 14-inch", type: "كمبيوتر محمول", serialNo: "APL-M2-1090", assignedDate: "2023-02-05" },
    ],
    documentsList: [
      { type: "national_id", title: "الهوية الوطنية السعودية", docNo: "1054321098", expiryDate: "2033-03-25", status: "valid" },
      { type: "contract", title: "عقد العمل الرقمي (قوى)", docNo: "QIWA-2023-88901", expiryDate: "2027-02-05", status: "valid" },
    ],
  },
  {
    id: "emp-06",
    employeeNo: "FOC-0106",
    firstNameAr: "عبدالله",
    lastNameAr: "الحربي",
    firstNameEn: "Abdullah",
    lastNameEn: "Al-Harbi",
    email: "abdullah.h@focus-hrms.com",
    personalEmail: "abdullah.personal@example.com",
    phone: "+966 55 600 0106",
    nationalIdOrIqama: "1043210987",
    nationalIdExpiry: "2028-06-30",
    passportNo: "KSA-88776655",
    passportExpiry: "2027-12-05",
    nationality: "سعودي",
    gender: "male",
    birthDate: "1988-10-14",
    maritalStatus: "married",
    bloodType: "A-",
    dependentsCount: 3,
    avatarUrl:
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80",
    subsidiaryId: "sub-01",
    subsidiaryName: "فوكس للتقنية",
    departmentId: "org-sales",
    departmentName: "إدارة المبيعات وتطوير الأعمال",
    jobTitleAr: "مدير المبيعات الإقليمي",
    jobTitleEn: "Regional Sales Manager",
    jobGrade: "L5 - مدير إدارة",
    costCenter: "CC-501 - المبيعات والتسويق",
    workType: "on_site",
    managerId: null,
    workLocationId: "loc-03",
    workLocationName: "فرع المنطقة الشرقية - الكورنيش (الخبر)",
    hireDate: "2018-11-01",
    contractStartDate: "2018-11-01",
    contractEndDate: "2026-11-01",
    qiwaContractNo: "QIWA-2018-77112",
    yearsOfService: 8,
    contractType: "full_time",
    status: "active",
    completionScore: 92,
    basicSalary: 26500,
    housingAllowance: 6625,
    transportAllowance: 1875,
    otherAllowances: 0,
    totalSalary: 35000,
    bankName: "البنك العربي الوطني (ANB)",
    iban: "SA40 3000 0001 7766 5544 0006",
    gosiNumber: "2211009988",
    gosiEmployeeDeduction: 2583.75,
    gosiEmployerContribution: 3113.75,
    nationalAddress: {
      buildingNo: "5512",
      street: "طريق الأمير فيصل بن فهد",
      district: "حي الحزام الذهبي",
      city: "الخبر",
      postalCode: "34432",
      additionalNo: "9910",
    },
    emergencyContact: {
      name: "ماجد الحربي",
      relation: "أخ",
      phone: "+966 50 666 7788",
    },
    educationDegree: "بكالوريوس إدارة الأعمال والتسويق الدولي",
    university: "جامعة الملك فهد للبترول والمعادن",
    graduationYear: 2010,
    certifications: ["Certified Sales Executive (CSE)", "Enterprise Solution Sales Mastery"],
    languages: ["العربية (اللغة الأم)", "الإنجليزية (ممتاز)"],
    assignedAssets: [
      { name: "HP EliteBook 840 G9", type: "كمبيوتر محمول", serialNo: "HP-ELT-9981", assignedDate: "2022-05-15" },
      { name: "هاتف iPhone 15 Pro أعمال", type: "هاتف محمول", serialNo: "APL-IPH-8821", assignedDate: "2023-10-01" },
    ],
    documentsList: [
      { type: "national_id", title: "الهوية الوطنية السعودية", docNo: "1043210987", expiryDate: "2028-06-30", status: "valid" },
      { type: "contract", title: "عقد العمل التنفيذي", docNo: "QIWA-2018-77112", expiryDate: "2026-11-01", status: "valid" },
    ],
  },
  {
    id: "emp-07",
    employeeNo: "FOC-0107",
    firstNameAr: "ريم",
    lastNameAr: "الدوسري",
    firstNameEn: "Reem",
    lastNameEn: "Al-Dossari",
    email: "reem.d@focus-hrms.com",
    personalEmail: "reem.personal@example.com",
    phone: "+966 55 700 0107",
    nationalIdOrIqama: "1032109876",
    nationalIdExpiry: "2030-09-12",
    passportNo: "KSA-66554433",
    passportExpiry: "2029-03-30",
    nationality: "سعودية",
    gender: "female",
    birthDate: "1994-05-19",
    maritalStatus: "single",
    bloodType: "B-",
    dependentsCount: 0,
    avatarUrl:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    subsidiaryId: "sub-01",
    subsidiaryName: "فوكس للتقنية",
    departmentId: "org-tech",
    departmentName: "قطاع هندسة البرمجيات والتقنية",
    jobTitleAr: "مهندسة ذكاء اصطناعي وتحليل بيانات",
    jobTitleEn: "AI & Data Specialist",
    jobGrade: "L4 - اختصاصي أول",
    costCenter: "CC-101 - تقنية المعلومات",
    workType: "hybrid",
    managerId: "emp-01",
    managerName: "خالد المهيري",
    workLocationId: "loc-01",
    workLocationName: "المقر الرئيسي - برج العليا (الرياض)",
    hireDate: "2022-08-14",
    contractStartDate: "2022-08-14",
    contractEndDate: "2026-08-14",
    qiwaContractNo: "QIWA-2022-99014",
    yearsOfService: 4,
    contractType: "full_time",
    status: "active",
    completionScore: 96,
    basicSalary: 20100,
    housingAllowance: 5025,
    transportAllowance: 1375,
    otherAllowances: 0,
    totalSalary: 26500,
    bankName: "مصرف الراجحي (Al Rajhi Bank)",
    iban: "SA44 8000 0201 9988 7766 0007",
    gosiNumber: "1100998877",
    gosiEmployeeDeduction: 1959.75,
    gosiEmployerContribution: 2361.75,
    nationalAddress: {
      buildingNo: "6610",
      street: "طريق الأمير محمد بن سلمان",
      district: "حي حطين",
      city: "الرياض",
      postalCode: "13512",
      additionalNo: "2201",
    },
    emergencyContact: {
      name: "سعد الدوسري",
      relation: "أب",
      phone: "+966 50 777 8899",
    },
    educationDegree: "ماجستير الذكاء الاصطناعي وتعلم الآلة",
    university: "جامعة الملك عبدالله للعلوم والتقنية (KAUST)",
    graduationYear: 2020,
    certifications: ["TensorFlow Developer Certificate", "Azure AI Engineer Associate", "Databricks ML Certified"],
    languages: ["العربية (اللغة الأم)", "الإنجليزية (طلاقة كاملة)"],
    assignedAssets: [
      { name: "MacBook Pro M3 Max 64GB RAM", type: "كمبيوتر محمول لأبحاث الذكاء الاصطناعي", serialNo: "APL-M3-AI99", assignedDate: "2023-11-20" },
    ],
    documentsList: [
      { type: "national_id", title: "الهوية الوطنية السعودية", docNo: "1032109876", expiryDate: "2030-09-12", status: "valid" },
      { type: "contract", title: "عقد العمل التقني (قوى)", docNo: "QIWA-2022-99014", expiryDate: "2026-08-14", status: "valid" },
    ],
  },
  {
    id: "emp-08",
    employeeNo: "FOC-0108",
    firstNameAr: "مشعل",
    lastNameAr: "الغامدي",
    firstNameEn: "Mishal",
    lastNameEn: "Al-Ghamdi",
    email: "mishal.g@focus-hrms.com",
    personalEmail: "mishal.personal@example.com",
    phone: "+966 55 800 0108",
    nationalIdOrIqama: "1021098765",
    nationalIdExpiry: "2034-01-10",
    passportNo: "KSA-22119988",
    passportExpiry: "2031-05-18",
    nationality: "سعودي",
    gender: "male",
    birthDate: "1996-09-08",
    maritalStatus: "single",
    bloodType: "O+",
    dependentsCount: 0,
    avatarUrl:
      "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
    subsidiaryId: "sub-03",
    subsidiaryName: "فوكس للعمليات اللوجستية",
    departmentId: "org-ops",
    departmentName: "إدارة العمليات والمشاريع",
    jobTitleAr: "منسق مشاريع ميدانية",
    jobTitleEn: "Operations Coordinator",
    jobGrade: "L2 - منسق تنفيذي",
    costCenter: "CC-301 - العمليات اللوجستية",
    workType: "on_site",
    managerId: "emp-03",
    managerName: "فيصل الزهراني",
    workLocationId: "loc-02",
    workLocationName: "فرع المنطقة الغربية - طريق الملك (جدة)",
    hireDate: "2024-01-02",
    contractStartDate: "2024-01-02",
    contractEndDate: "2026-01-02",
    qiwaContractNo: "QIWA-2024-11099",
    yearsOfService: 2,
    contractType: "full_time",
    status: "probation",
    completionScore: 78,
    basicSalary: 12700,
    housingAllowance: 3000,
    transportAllowance: 800,
    otherAllowances: 0,
    totalSalary: 16500,
    bankName: "البنك الأهلي السعودي (SNB)",
    iban: "SA12 1000 0001 6655 4433 0008",
    gosiNumber: "0099887766",
    gosiEmployeeDeduction: 1238.25,
    gosiEmployerContribution: 1492.25,
    nationalAddress: {
      buildingNo: "1109",
      street: "طريق المدينة المنورة",
      district: "حي الروضة",
      city: "جدة",
      postalCode: "23431",
      additionalNo: "7710",
    },
    emergencyContact: {
      name: "طارق الغامدي",
      relation: "أخ",
      phone: "+966 50 888 1122",
    },
    educationDegree: "بكالوريوس الهندسة الصناعية وإدارة النظم",
    university: "جامعة الملك عبدالعزيز",
    graduationYear: 2021,
    certifications: ["CAPM - Certified Associate in Project Management", "OSHA 30-Hour Safety"],
    languages: ["العربية (اللغة الأم)", "الإنجليزية (جيد)"],
    assignedAssets: [
      { name: "Lenovo ThinkPad T14", type: "كمبيوتر محمول ميداني", serialNo: "LNV-T14-5501", assignedDate: "2024-01-02" },
    ],
    documentsList: [
      { type: "national_id", title: "الهوية الوطنية السعودية", docNo: "1021098765", expiryDate: "2034-01-10", status: "valid" },
      { type: "contract", title: "عقد العمل تحت التجربة (قوى)", docNo: "QIWA-2024-11099", expiryDate: "2026-01-02", status: "valid" },
    ],
  },
  {
    id: "emp-09",
    employeeNo: "FOC-0109",
    firstNameAr: "طارق",
    lastNameAr: "المهدي",
    firstNameEn: "Tarek",
    lastNameEn: "El-Mahdy",
    email: "tarek.m@focus-hrms.com",
    personalEmail: "tarek.personal@example.com",
    phone: "+966 55 900 0109",
    nationalIdOrIqama: "2389102938",
    nationalIdExpiry: "2026-10-15",
    passportNo: "EGY-A2991029",
    passportExpiry: "2027-06-20",
    nationality: "مصري",
    gender: "male",
    birthDate: "1991-03-14",
    maritalStatus: "married",
    bloodType: "A+",
    dependentsCount: 2,
    avatarUrl:
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80",
    subsidiaryId: "sub-01",
    subsidiaryName: "فوكس للتقنية",
    departmentId: "org-tech",
    departmentName: "قطاع هندسة البرمجيات والتقنية",
    jobTitleAr: "مهندس بنية تحتية سحابية وDevOps أول",
    jobTitleEn: "Lead Cloud & DevOps Engineer",
    jobGrade: "L4 - اختصاصي أول",
    costCenter: "CC-101 - تقنية المعلومات",
    workType: "hybrid",
    managerId: "emp-01",
    managerName: "خالد المهيري",
    workLocationId: "loc-01",
    workLocationName: "المقر الرئيسي - برج العليا (الرياض)",
    hireDate: "2022-04-10",
    contractStartDate: "2022-04-10",
    contractEndDate: "2026-04-10",
    qiwaContractNo: "QIWA-2022-88129",
    yearsOfService: 4,
    contractType: "full_time",
    status: "active",
    completionScore: 94,
    basicSalary: 17000,
    housingAllowance: 4250,
    transportAllowance: 1250,
    otherAllowances: 0,
    totalSalary: 22500,
    bankName: "مصرف الراجحي (Al Rajhi Bank)",
    iban: "SA44 8000 0201 1122 3344 0009",
    gosiNumber: "9988112233",
    gosiEmployeeDeduction: 0,
    gosiEmployerContribution: 340.0,
    nationalAddress: {
      buildingNo: "3312",
      street: "طريق الملك فهد",
      district: "حي العقيق",
      city: "الرياض",
      postalCode: "13511",
      additionalNo: "8801",
    },
    emergencyContact: {
      name: "ياسمين المهدي",
      relation: "زوجة",
      phone: "+966 54 990 0112",
    },
    educationDegree: "بكالوريوس هندسة الحاسبات والنظم",
    university: "جامعة عين شمس - القاهرة",
    graduationYear: 2013,
    certifications: ["Certified Kubernetes Administrator (CKA)", "AWS DevOps Engineer Professional", "HashiCorp Certified Terraform"],
    languages: ["العربية (اللغة الأم)", "الإنجليزية (طلاقة كاملة)"],
    assignedAssets: [
      { name: "Dell Precision 5570 Workstation", type: "محطة عمل متطورة", serialNo: "DEL-PRC-1109", assignedDate: "2022-04-10" },
    ],
    documentsList: [
      { type: "iqama", title: "بطاقة الإقامة النظامية (مقيم)", docNo: "2389102938", expiryDate: "2026-10-15", status: "expiring" },
      { type: "passport", title: "جواز السفر المصري", docNo: "EGY-A2991029", expiryDate: "2027-06-20", status: "valid" },
      { type: "contract", title: "عقد العمل الدولي الموثق (قوى)", docNo: "QIWA-2022-88129", expiryDate: "2026-04-10", status: "valid" },
    ],
  },
  {
    id: "emp-10",
    employeeNo: "FOC-0110",
    firstNameAr: "فاطمة",
    lastNameAr: "النجار",
    firstNameEn: "Fatima",
    lastNameEn: "Al-Najjar",
    email: "fatima.n@focus-hrms.com",
    personalEmail: "fatima.personal@example.com",
    phone: "+966 55 110 0110",
    nationalIdOrIqama: "2490192837",
    nationalIdExpiry: "2026-09-28",
    passportNo: "JOR-P8819201",
    passportExpiry: "2028-02-14",
    nationality: "أردنية",
    gender: "female",
    birthDate: "1993-12-04",
    maritalStatus: "married",
    bloodType: "AB-",
    dependentsCount: 1,
    avatarUrl:
      "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150&auto=format&fit=crop&q=80",
    subsidiaryId: "sub-01",
    subsidiaryName: "فوكس للتقنية",
    departmentId: "org-tech",
    departmentName: "قطاع هندسة البرمجيات والتقنية",
    jobTitleAr: "مديرة ضمان جودة البرمجيات (QA Lead)",
    jobTitleEn: "Software Quality Assurance Lead",
    jobGrade: "L4 - قائد فريق",
    costCenter: "CC-101 - تقنية المعلومات",
    workType: "on_site",
    managerId: "emp-01",
    managerName: "خالد المهيري",
    workLocationId: "loc-01",
    workLocationName: "المقر الرئيسي - برج العليا (الرياض)",
    hireDate: "2023-05-15",
    contractStartDate: "2023-05-15",
    contractEndDate: "2027-05-15",
    qiwaContractNo: "QIWA-2023-77610",
    yearsOfService: 3,
    contractType: "full_time",
    status: "active",
    completionScore: 91,
    basicSalary: 16000,
    housingAllowance: 4000,
    transportAllowance: 1000,
    otherAllowances: 0,
    totalSalary: 21000,
    bankName: "البنك العربي الوطني (ANB)",
    iban: "SA40 3000 0001 5544 3322 0010",
    gosiNumber: "8877665544",
    gosiEmployeeDeduction: 0,
    gosiEmployerContribution: 320.0,
    nationalAddress: {
      buildingNo: "8810",
      street: "شارع الضباب",
      district: "حي السليمانية",
      city: "الرياض",
      postalCode: "12241",
      additionalNo: "4410",
    },
    emergencyContact: {
      name: "رامي النجار",
      relation: "زوج",
      phone: "+966 54 112 3344",
    },
    educationDegree: "بكالوريوس هندسة البرمجيات ونظم المعلومات",
    university: "الجامعة الأردنية - عمان",
    graduationYear: 2015,
    certifications: ["ISTQB Certified Tester Full Advanced Level", "Selenium Automated Testing Mastery"],
    languages: ["العربية (اللغة الأم)", "الإنجليزية (ممتاز)"],
    assignedAssets: [
      { name: "HP ZBook Firefly 14 G10", type: "كمبيوتر محمول", serialNo: "HP-ZB-9910", assignedDate: "2023-05-15" },
    ],
    documentsList: [
      { type: "iqama", title: "بطاقة الإقامة (مقيم)", docNo: "2490192837", expiryDate: "2026-09-28", status: "expiring" },
      { type: "passport", title: "جواز السفر الأردني", docNo: "JOR-P8819201", expiryDate: "2028-02-14", status: "valid" },
    ],
  },
];

// ----------------------------------------------------------------------------
// M04: RBAC Roles & Permission Presets
// ----------------------------------------------------------------------------
export const mockRoles: RoleDefinition[] = [
  {
    id: "role-superadmin",
    code: "super_admin",
    nameAr: "مشرف النظام العام (Super Admin)",
    nameEn: "Super Administrator",
    descriptionAr: "صلاحيات كاملة وغير مقيدة على كافة الوحدات والإعدادات وسجلات التدقيق والأمان.",
    descriptionEn:
      "Unrestricted full access across all organization modules, security and system configs.",
    isSystem: true,
    userCount: 2,
    permissions: [],
  },
  {
    id: "role-hrmanager",
    code: "hr_manager",
    nameAr: "مدير الموارد البشرية (HR Manager)",
    nameEn: "Human Resources Manager",
    descriptionAr:
      "إدارة كاملة لملفات الموظفين، عقود العمل، الإجازات، الحضور، مسارات التوظيف والتقارير.",
    descriptionEn:
      "Comprehensive management of employee lifecycle, policies, leaves, attendance, and ATS.",
    isSystem: true,
    userCount: 4,
    permissions: [],
  },
  {
    id: "role-payroll",
    code: "payroll_officer",
    nameAr: "مشرف مسيرات الرواتب (Payroll Lead)",
    nameEn: "Payroll Officer",
    descriptionAr:
      "إعداد ومراجعة وتأكيد مسيرات الرواتب الشهرية وتوليد قسائم الدفع وملفات البنوك WPS.",
    descriptionEn:
      "Execution, review, and locking of monthly payroll runs, WPS export, and payslips.",
    isSystem: true,
    userCount: 3,
    permissions: [],
  },
  {
    id: "role-manager",
    code: "line_manager",
    nameAr: "مدير مباشر (Line Manager)",
    nameEn: "Line / Department Manager",
    descriptionAr: "اعتماد طلبات الفريق المباشر، متابعة حضورهم، وجدولة الدوام وتقييم الأداء.",
    descriptionEn:
      "Approvals for team requests, attendance monitoring, scheduling, and 360 performance reviews.",
    isSystem: true,
    userCount: 8,
    permissions: [],
  },
  {
    id: "role-employee",
    code: "employee",
    nameAr: "الخدمة الذاتية للموظف (Employee ESS)",
    nameEn: "Employee Self-Service",
    descriptionAr:
      "الوصول للبيانات الشخصية، تقديم طلبات الإجازات والسلف والمصروفات، وتسجيل الحضور الذاتي.",
    descriptionEn:
      "Self-service submission of leaves, advances, expenses, attendance correction and payslip view.",
    isSystem: true,
    userCount: 140,
    permissions: [],
  },
];

// ----------------------------------------------------------------------------
// M05: Approval Chains & Service Requests
// ----------------------------------------------------------------------------
export const mockApprovalChains: ApprovalChain[] = [
  {
    id: "chain-leave",
    requestType: "leave",
    nameAr: "سلسلة اعتمادات الإجازات الاعتيادية",
    nameEn: "Standard Leave Approval Chain",
    scopeType: "all_employees",
    isDefault: true,
    status: "active",
    steps: [
      {
        sequence: 1,
        resolverType: "direct_manager",
        stepNameAr: "موافقة المدير المباشر",
        stepNameEn: "Direct Manager Approval",
      },
      {
        sequence: 2,
        resolverType: "hr_manager",
        stepNameAr: "مراجعة الموارد البشرية وتأكيد الرصيد",
        stepNameEn: "HR Verification & Balance Lock",
      },
    ],
  },
  {
    id: "chain-expense",
    requestType: "expense_claim",
    nameAr: "سلسلة اعتماد النفقات والمصروفات",
    nameEn: "Expense Claims Approval Chain",
    scopeType: "all_employees",
    isDefault: true,
    status: "active",
    steps: [
      {
        sequence: 1,
        resolverType: "direct_manager",
        stepNameAr: "موافقة المدير المباشر",
        stepNameEn: "Direct Manager Approval",
      },
      {
        sequence: 2,
        resolverType: "finance_manager",
        stepNameAr: "موافقة الإدارة المالية وتدقيق الفواتير",
        stepNameEn: "Finance Audit & Payment Authorization",
      },
    ],
  },
  {
    id: "chain-loan",
    requestType: "loan_advance",
    nameAr: "سلسلة طلبات السلف الشهرية",
    nameEn: "Monthly Advance Approval Chain",
    scopeType: "all_employees",
    isDefault: true,
    status: "active",
    steps: [
      {
        sequence: 1,
        resolverType: "hr_manager",
        stepNameAr: "فحص أهلية الموظف وسياسة السلفة",
        stepNameEn: "HR Policy & Eligibility Check",
      },
      {
        sequence: 2,
        resolverType: "finance_manager",
        stepNameAr: "اعتماد الصرف وجدول الأقساط",
        stepNameEn: "Finance & Payroll Schedule Approval",
      },
    ],
  },
];

export const mockRequests: ServiceRequest[] = [
  {
    id: "req-101",
    referenceNo: "REQ-2026-0891",
    type: "leave",
    requesterId: "emp-05",
    requesterName: "محمد الشمري",
    requesterJobTitle: "مطور واجهات أمامية أول",
    requesterAvatar:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    departmentName: "قطاع هندسة البرمجيات والتقنية",
    status: "pending_approval",
    currentStepIndex: 1,
    totalSteps: 2,
    currentApproverRole: "المدير المباشر (خالد المهيري)",
    submittedAt: "2026-08-28T09:30:00Z",
    updatedAt: "2026-08-28T09:30:00Z",
    payload: {
      leaveTypeId: "leave-annual",
      leaveTypeNameAr: "إجازة سنوية مدفوعة",
      startDate: "2026-09-05",
      endDate: "2026-09-12",
      totalDays: 6,
      reason: "إجازة سنوية للراحة وظروف عائلية",
      replacementEmployeeName: "ريم الدوسري",
    },
    timeline: [
      {
        id: "tl-1",
        stepNumber: 1,
        actorId: "emp-05",
        actorName: "محمد الشمري",
        actorRole: "مقدم الطلب",
        action: "submitted",
        note: "تم تقديم طلب إجازة سنوية لمدة 6 أيام عمل",
        timestamp: "2026-08-28T09:30:00Z",
      },
    ],
  },
  {
    id: "req-102",
    referenceNo: "REQ-2026-0892",
    type: "expense_claim",
    requesterId: "emp-07",
    requesterName: "ريم الدوسري",
    requesterJobTitle: "مهندسة ذكاء اصطناعي",
    requesterAvatar:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    departmentName: "قطاع هندسة البرمجيات والتقنية",
    status: "pending_approval",
    currentStepIndex: 2,
    totalSteps: 2,
    currentApproverRole: "الإدارة المالية (نورة القحطاني)",
    submittedAt: "2026-08-26T14:15:00Z",
    updatedAt: "2026-08-27T11:00:00Z",
    payload: {
      categoryNameAr: "مصروفات مؤتمرات وتدريب",
      amount: 3850,
      currency: "SAR",
      merchantName: "مؤتمر الذكاء الاصطناعي العالمي - الرياض",
      description: "رسوم حضور ورشة عمل متقدمة في الذكاء الاصطناعي التوليدي",
    },
    timeline: [
      {
        id: "tl-2",
        stepNumber: 1,
        actorId: "emp-07",
        actorName: "ريم الدوسري",
        actorRole: "مقدم الطلب",
        action: "submitted",
        timestamp: "2026-08-26T14:15:00Z",
      },
      {
        id: "tl-3",
        stepNumber: 1,
        actorId: "emp-01",
        actorName: "خالد المهيري",
        actorRole: "المدير المباشر",
        action: "approved",
        note: "معتمد لأهمية الدورة للمشروع الحالي",
        timestamp: "2026-08-27T11:00:00Z",
      },
    ],
  },
  {
    id: "req-103",
    referenceNo: "REQ-2026-0885",
    type: "loan_advance",
    requesterId: "emp-08",
    requesterName: "مشعل الغامدي",
    requesterJobTitle: "منسق مشاريع",
    departmentName: "إدارة العمليات والمشاريع",
    status: "approved",
    currentStepIndex: 2,
    totalSteps: 2,
    submittedAt: "2026-08-20T10:00:00Z",
    updatedAt: "2026-08-22T16:00:00Z",
    payload: {
      principalAmount: 6000,
      monthlyInstallment: 1000,
      installmentsCount: 6,
      reason: "سلفة طارئة لصيانة السيارة",
    },
    timeline: [
      {
        id: "tl-4",
        stepNumber: 1,
        actorId: "emp-08",
        actorName: "مشعل الغامدي",
        actorRole: "مقدم الطلب",
        action: "submitted",
        timestamp: "2026-08-20T10:00:00Z",
      },
      {
        id: "tl-5",
        stepNumber: 1,
        actorId: "emp-04",
        actorName: "سارة العتيبي",
        actorRole: "مدير الموارد البشرية",
        action: "approved",
        note: "مستوفي لشروط السلفة وضمن الحد المسموح",
        timestamp: "2026-08-21T09:30:00Z",
      },
      {
        id: "tl-6",
        stepNumber: 2,
        actorId: "emp-02",
        actorName: "نورة القحطاني",
        actorRole: "مدير المالية",
        action: "approved",
        note: "تم إدراج الاستقطاع الشهري بمسير الرواتب بدءاً من مسير سبتمبر",
        timestamp: "2026-08-22T16:00:00Z",
      },
    ],
  },
];

// ----------------------------------------------------------------------------
// M06: Leave Types & Policies
// ----------------------------------------------------------------------------
export const mockLeaveTypes: LeaveTypePolicy[] = [
  {
    id: "leave-annual",
    code: "ANNUAL",
    nameAr: "إجازة سنوية اعتيادية",
    nameEn: "Annual Paid Leave",
    color: "#0284c7", // Sky Blue
    isPaid: true,
    deductFromWorkingDaysOnly: true,
    maxDaysPerYear: 30,
    allowHalfDay: true,
    allowNegativeBalance: false,
    requiresAttachment: false,
    accrualMethod: "yearly_frontloaded",
    carryoverLimitDays: 10,
    status: "active",
  },
  {
    id: "leave-sick",
    code: "SICK",
    nameAr: "إجازة مرضية",
    nameEn: "Sick Leave",
    color: "#e11d48", // Rose Red
    isPaid: true,
    deductFromWorkingDaysOnly: false,
    maxDaysPerYear: 120, // Saudi labor law tiers
    allowHalfDay: false,
    allowNegativeBalance: false,
    requiresAttachment: true,
    accrualMethod: "yearly_frontloaded",
    carryoverLimitDays: 0,
    status: "active",
  },
  {
    id: "leave-emergency",
    code: "EMERGENCY",
    nameAr: "إجازة طارئة / وفاة / زواج",
    nameEn: "Emergency / Compassionate Leave",
    color: "#d97706", // Amber
    isPaid: true,
    deductFromWorkingDaysOnly: true,
    maxDaysPerYear: 5,
    allowHalfDay: false,
    allowNegativeBalance: false,
    requiresAttachment: true,
    accrualMethod: "yearly_frontloaded",
    carryoverLimitDays: 0,
    status: "active",
  },
  {
    id: "leave-unpaid",
    code: "UNPAID",
    nameAr: "إجازة غير مدفوعة الأجر",
    nameEn: "Unpaid Leave",
    color: "#64748b", // Slate Gray
    isPaid: false,
    deductFromWorkingDaysOnly: false,
    maxDaysPerYear: 60,
    allowHalfDay: true,
    allowNegativeBalance: false,
    requiresAttachment: false,
    accrualMethod: "contract_anniversary",
    carryoverLimitDays: 0,
    status: "active",
  },
];

export const mockEmployeeLeaveBalances: EmployeeLeaveBalance[] = [
  {
    leaveTypeId: "leave-annual",
    leaveTypeNameAr: "إجازة سنوية اعتيادية",
    leaveTypeNameEn: "Annual Paid Leave",
    color: "#0284c7",
    annualEntitlement: 30,
    accruedDays: 20,
    usedDays: 8,
    reservedDays: 6,
    carriedOverDays: 4,
    availableBalance: 10,
  },
  {
    leaveTypeId: "leave-sick",
    leaveTypeNameAr: "إجازة مرضية",
    leaveTypeNameEn: "Sick Leave",
    color: "#e11d48",
    annualEntitlement: 30,
    accruedDays: 30,
    usedDays: 2,
    reservedDays: 0,
    carriedOverDays: 0,
    availableBalance: 28,
  },
  {
    leaveTypeId: "leave-emergency",
    leaveTypeNameAr: "إجازة طارئة",
    leaveTypeNameEn: "Emergency Leave",
    color: "#d97706",
    annualEntitlement: 5,
    accruedDays: 5,
    usedDays: 1,
    reservedDays: 0,
    carriedOverDays: 0,
    availableBalance: 4,
  },
];

// ----------------------------------------------------------------------------
// M07, M08, M09: Shifts, Schedules & Attendance Records
// ----------------------------------------------------------------------------
export const mockShifts: ShiftDefinition[] = [
  {
    id: "shift-morning",
    code: "SHF-AM",
    nameAr: "الوردية الصباحية المعتادة (8 ساعات)",
    nameEn: "Standard Morning Shift",
    color: "#10b981", // Emerald Green
    type: "fixed",
    startTime: "08:00",
    endTime: "17:00",
    graceMinutesArrival: 15,
    graceMinutesDeparture: 15,
    allowSinglePunch: false,
    overtimeEligible: true,
  },
  {
    id: "shift-flex",
    code: "SHF-FLX",
    nameAr: "الدوام المرن للتقنية والأبحاث",
    nameEn: "Flexible Tech Shift (8 hrs)",
    color: "#6366f1", // Indigo
    type: "flexible",
    startTime: "07:30",
    endTime: "19:00",
    flexibleHours: 8,
    graceMinutesArrival: 30,
    graceMinutesDeparture: 30,
    allowSinglePunch: false,
    overtimeEligible: true,
  },
  {
    id: "shift-split",
    code: "SHF-SPLIT",
    nameAr: "فترتان مجزأة (صباحي / مسائي للمبيعات)",
    nameEn: "Split Sales Shift",
    color: "#f59e0b", // Amber
    type: "split",
    startTime: "09:00",
    endTime: "13:00",
    splitSecondStartTime: "17:00",
    splitSecondEndTime: "21:00",
    graceMinutesArrival: 10,
    graceMinutesDeparture: 10,
    allowSinglePunch: false,
    overtimeEligible: true,
  },
];

export const mockAttendanceRecords: DailyAttendanceRecord[] = [
  {
    id: "att-01",
    employeeId: "emp-01",
    employeeNo: "FOC-0101",
    employeeName: "خالد المهيري",
    departmentName: "قطاع هندسة البرمجيات والتقنية",
    workDate: "2026-08-30",
    scheduledShift: "الوردية الصباحية المعتادة",
    scheduledIn: "08:00",
    scheduledOut: "17:00",
    actualIn: "08:04",
    actualOut: "17:15",
    status: "present",
    lateMinutes: 0,
    earlyDepartureMinutes: 0,
    workedHours: 9.18,
    overtimeHours: 0.25,
    punchSource: "mobile_gps",
    geofenceValid: true,
    violationsCount: 0,
    reviewedByPayroll: false,
  },
  {
    id: "att-02",
    employeeId: "emp-05",
    employeeNo: "FOC-0105",
    employeeName: "محمد الشمري",
    departmentName: "قطاع هندسة البرمجيات والتقنية",
    workDate: "2026-08-30",
    scheduledShift: "الدوام المرن للتقنية",
    scheduledIn: "08:00",
    scheduledOut: "17:00",
    actualIn: "08:42",
    actualOut: "17:00",
    status: "late",
    lateMinutes: 42,
    earlyDepartureMinutes: 0,
    workedHours: 8.3,
    overtimeHours: 0,
    punchSource: "biometric_device",
    geofenceValid: true,
    violationsCount: 1,
    reviewedByPayroll: false,
  },
  {
    id: "att-03",
    employeeId: "emp-07",
    employeeNo: "FOC-0107",
    employeeName: "ريم الدوسري",
    departmentName: "قطاع هندسة البرمجيات والتقنية",
    workDate: "2026-08-30",
    scheduledShift: "الدوام المرن للتقنية",
    scheduledIn: "08:00",
    scheduledOut: "17:00",
    actualIn: "07:55",
    actualOut: "17:05",
    status: "present",
    lateMinutes: 0,
    earlyDepartureMinutes: 0,
    workedHours: 9.16,
    overtimeHours: 0,
    punchSource: "mobile_gps",
    geofenceValid: true,
    violationsCount: 0,
    reviewedByPayroll: false,
  },
  {
    id: "att-04",
    employeeId: "emp-08",
    employeeNo: "FOC-0108",
    employeeName: "مشعل الغامدي",
    departmentName: "إدارة العمليات والمشاريع",
    workDate: "2026-08-30",
    scheduledShift: "الوردية الصباحية المعتادة",
    scheduledIn: "08:00",
    scheduledOut: "17:00",
    actualIn: undefined,
    actualOut: undefined,
    status: "absent",
    lateMinutes: 0,
    earlyDepartureMinutes: 0,
    workedHours: 0,
    overtimeHours: 0,
    punchSource: "manual_admin",
    geofenceValid: false,
    violationsCount: 1,
    reviewedByPayroll: false,
  },
];

// ----------------------------------------------------------------------------
// M10 & M11: Payroll Runs & Details
// ----------------------------------------------------------------------------
export const mockPayrollGroups: PayrollGroup[] = [
  {
    id: "pg-monthly",
    nameAr: "مجموعة الرواتب العامة (المنشأة الرئيسية)",
    nameEn: "General Headquarter Payroll",
    calculationBasis: "fixed_30_days",
    cutoffDay: 25,
    payday: 28,
    currency: "SAR",
    employeeCount: 120,
  },
  {
    id: "pg-ops",
    nameAr: "مجموعة رواتب العمليات الميدانية واللوجستية",
    nameEn: "Operations & Field Payroll",
    calculationBasis: "calendar_days",
    cutoffDay: 24,
    payday: 27,
    currency: "SAR",
    employeeCount: 65,
  },
];

export const mockPayrollRuns: PayrollRun[] = [
  {
    id: "pr-2026-08",
    payrollGroupId: "pg-monthly",
    payrollGroupName: "مجموعة الرواتب العامة",
    periodYear: 2026,
    periodMonth: 8,
    status: "ready_for_review",
    totalEmployees: 120,
    totalBasicSalary: 1680000,
    totalAllowances: 420000,
    totalOvertimeAmount: 48500,
    totalDeductions: 198200,
    totalNetSalary: 1950300,
    totalEmployerGosi: 215400,
  },
  {
    id: "pr-2026-07",
    payrollGroupId: "pg-monthly",
    payrollGroupName: "مجموعة الرواتب العامة",
    periodYear: 2026,
    periodMonth: 7,
    status: "confirmed_locked",
    totalEmployees: 118,
    totalBasicSalary: 1650000,
    totalAllowances: 412500,
    totalOvertimeAmount: 39400,
    totalDeductions: 192800,
    totalNetSalary: 1909100,
    totalEmployerGosi: 211200,
    lockedAt: "2026-07-27T18:00:00Z",
    paidAt: "2026-07-28T09:00:00Z",
  },
];

export const mockPayrollDetails: EmployeePayrollDetail[] = [
  {
    id: "pd-01",
    payrollRunId: "pr-2026-08",
    employeeId: "emp-01",
    employeeNo: "FOC-0101",
    employeeName: "خالد المهيري",
    jobTitle: "رئيس قسم الهندسة البرمجية",
    departmentName: "قطاع هندسة البرمجيات والتقنية",
    bankName: "مصرف الراجحي",
    iban: "SA4480000201608010001234",
    basicSalary: 18500,
    housingAllowance: 4625,
    transportAllowance: 1375,
    otherAllowances: 0,
    overtimeHours: 6,
    overtimeAmount: 918.75,
    retroAdjustments: 0,
    bonusAmount: 0,
    grossSalary: 25418.75,
    unpaidLeaveDeduction: 0,
    absenceLateDeduction: 0,
    loanInstallmentDeduction: 0,
    gosiEmployeeDeduction: 2254.69,
    otherDeductions: 0,
    totalDeductions: 2254.69,
    netSalary: 23164.06,
  },
  {
    id: "pd-02",
    payrollRunId: "pr-2026-08",
    employeeId: "emp-05",
    employeeNo: "FOC-0105",
    employeeName: "محمد الشمري",
    jobTitle: "مطور واجهات أمامية أول",
    departmentName: "قطاع هندسة البرمجيات والتقنية",
    bankName: "البنك الأهلي السعودي (SNB)",
    iban: "SA1210000001234567890123",
    basicSalary: 14500,
    housingAllowance: 3625,
    transportAllowance: 875,
    otherAllowances: 0,
    overtimeHours: 0,
    overtimeAmount: 0,
    retroAdjustments: 0,
    bonusAmount: 0,
    grossSalary: 19000,
    unpaidLeaveDeduction: 0,
    absenceLateDeduction: 154.2,
    loanInstallmentDeduction: 0,
    gosiEmployeeDeduction: 1767.19,
    otherDeductions: 0,
    totalDeductions: 1921.39,
    netSalary: 17078.61,
  },
  {
    id: "pd-03",
    payrollRunId: "pr-2026-08",
    employeeId: "emp-08",
    employeeNo: "FOC-0108",
    employeeName: "مشعل الغامدي",
    jobTitle: "منسق مشاريع",
    departmentName: "إدارة العمليات والمشاريع",
    bankName: "بنك الرياض",
    iban: "SA6520000009876543210987",
    basicSalary: 12700,
    housingAllowance: 3175,
    transportAllowance: 625,
    otherAllowances: 0,
    overtimeHours: 0,
    overtimeAmount: 0,
    retroAdjustments: 0,
    bonusAmount: 0,
    grossSalary: 16500,
    unpaidLeaveDeduction: 0,
    absenceLateDeduction: 550.0,
    loanInstallmentDeduction: 1000.0,
    gosiEmployeeDeduction: 1547.81,
    otherDeductions: 0,
    totalDeductions: 3097.81,
    netSalary: 13402.19,
  },
];

export const mockLoans: LoanRecord[] = [
  {
    id: "loan-01",
    employeeId: "emp-08",
    employeeName: "مشعل الغامدي",
    loanType: "personal_advance",
    principalAmount: 6000,
    monthlyInstallment: 1000,
    totalInstallments: 6,
    paidInstallments: 0,
    remainingBalance: 6000,
    startDate: "2026-09-01",
    status: "active",
  },
];

export const mockSettlements: FinalSettlementRecord[] = [
  {
    id: "set-01",
    employeeId: "emp-09",
    employeeName: "ماجد السبيعي (منتهي الخدمة)",
    terminationDate: "2026-08-15",
    noticePeriodServed: true,
    serviceYears: 4,
    serviceMonths: 6,
    eosbAmount: 42750,
    leaveBalancePayoutDays: 14,
    leaveBalancePayoutAmount: 8866.67,
    pendingSalaryAmount: 9500,
    loanDeductionAmount: 0,
    assetClearanceComplete: true,
    netSettlementAmount: 61116.67,
    status: "approved",
  },
];

// ----------------------------------------------------------------------------
// M12: Expenses & Claims
// ----------------------------------------------------------------------------
export const mockExpenseCategories: ExpenseCategory[] = [
  {
    id: "exp-cat-travel",
    nameAr: "سفر وانتداب وتذاكر طيران",
    nameEn: "Business Travel & Flights",
    icon: "Plane",
    maxLimitWarning: 5000,
    maxLimitBlock: 15000,
    requiresReceipt: true,
  },
  {
    id: "exp-cat-hotel",
    nameAr: "إقامة فندقية وضيافة عمل",
    nameEn: "Hotel & Hospitality",
    icon: "Hotel",
    maxLimitWarning: 1500,
    maxLimitBlock: 4000,
    requiresReceipt: true,
  },
  {
    id: "exp-cat-training",
    nameAr: "دورات تدريبية وشهادات مهنية",
    nameEn: "Training & Professional Certifications",
    icon: "GraduationCap",
    maxLimitWarning: 4000,
    maxLimitBlock: 10000,
    requiresReceipt: true,
  },
  {
    id: "exp-cat-supplies",
    nameAr: "أدوات ومستلزمات مكتبية وتقنية",
    nameEn: "Office & Tech Supplies",
    icon: "Laptop",
    maxLimitWarning: 1000,
    maxLimitBlock: 3000,
    requiresReceipt: true,
  },
];

export const mockExpenseClaims: ExpenseClaim[] = [
  {
    id: "claim-01",
    employeeId: "emp-07",
    categoryId: "exp-cat-training",
    categoryNameAr: "دورات تدريبية وشهادات مهنية",
    categoryNameEn: "Training & Certifications",
    amount: 3850,
    currency: "SAR",
    spentAt: "2026-08-25",
    merchantName: "القمة العالمية للذكاء الاصطناعي",
    description: "تسجيل ورشة عمل الهندسة المتقدمة للذكاء الاصطناعي",
    policyWarningTriggered: false,
    status: "submitted",
  },
  {
    id: "claim-02",
    employeeId: "emp-06",
    categoryId: "exp-cat-travel",
    categoryNameAr: "سفر وانتداب وتذاكر طيران",
    categoryNameEn: "Business Travel",
    amount: 1450,
    currency: "SAR",
    spentAt: "2026-08-20",
    merchantName: "طيران ناس - رحلة الرياض / الخبر",
    description: "زيارة عملاء قطاع التجزئة بالمنطقة الشرقية",
    policyWarningTriggered: false,
    status: "approved",
  },
];

// ----------------------------------------------------------------------------
// M13: Performance Management 360°
// ----------------------------------------------------------------------------
export const mockPerformanceCycles: PerformanceCycle[] = [
  {
    id: "perf-2026-q3",
    titleAr: "دورة تقييم الأداء للربع الثالث 2026 (360° Review)",
    titleEn: "Q3 2026 Multi-Rater Performance Review",
    periodType: "quarterly",
    startDate: "2026-08-15",
    endDate: "2026-09-30",
    status: "active",
    participantsCount: 84,
    completionRate: 64,
  },
];

export const mockEvaluations: EvaluationRecord[] = [
  {
    id: "eval-01",
    cycleId: "perf-2026-q3",
    employeeId: "emp-05",
    employeeName: "محمد الشمري",
    evaluatorId: "emp-01",
    evaluatorName: "خالد المهيري",
    evaluationType: "manager",
    overallScore: 4.6,
    status: "submitted",
    submittedAt: "2026-08-29T10:30:00Z",
  },
  {
    id: "eval-02",
    cycleId: "perf-2026-q3",
    employeeId: "emp-05",
    employeeName: "محمد الشمري",
    evaluatorId: "emp-07",
    evaluatorName: "ريم الدوسري",
    evaluationType: "peer",
    overallScore: 4.8,
    status: "submitted",
    submittedAt: "2026-08-28T15:20:00Z",
  },
];

// ----------------------------------------------------------------------------
// M14: Workforce Planning
// ----------------------------------------------------------------------------
export const mockWorkforcePlans: WorkforcePlan[] = [
  {
    id: "wp-2026",
    titleAr: "خطة التوظيف وتوسع القوى العاملة 2026 / 2027",
    titleEn: "Annual Strategic Workforce Plan 2026/2027",
    year: 2026,
    departmentId: "org-tech",
    departmentName: "قطاع هندسة البرمجيات والتقنية",
    currentHeadcount: 48,
    plannedHires: 14,
    plannedExits: 2,
    targetHeadcount: 60,
    currentBudget: 8500000,
    projectedCost: 11200000,
    status: "approved",
  },
];

// ----------------------------------------------------------------------------
// M15: ATS & Recruitment Pipeline
// ----------------------------------------------------------------------------
export const mockJobOpenings: JobOpening[] = [
  {
    id: "job-01",
    titleAr: "مطور واجهات ومصمم تجربة مستخدم (Full-Stack UI Engineer)",
    titleEn: "Senior Full-Stack UI Engineer",
    departmentId: "org-tech",
    departmentName: "قطاع هندسة البرمجيات والتقنية",
    locationId: "loc-01",
    locationName: "المقر الرئيسي (الرياض)",
    employmentType: "full_time",
    openingsCount: 3,
    filledCount: 1,
    publishedStatus: "published",
    salaryMin: 18000,
    salaryMax: 24000,
    descriptionAr:
      "نبحث عن مهندس برمجيات محترف لبناء واجهات نظم إدارة الموارد البشرية السحابية باستخدام React وTypeScript.",
    descriptionEn:
      "Looking for a senior frontend developer to scale enterprise SaaS portals using React and modern toolchains.",
    requirementsAr:
      "خبرة لا تقل عن 4 سنوات في React وTypeScript ومعرفة عميقة بـ RTL والتصاميم التفاعلية.",
    requirementsEn: "4+ years of React, TypeScript, Tailwind CSS and state management experience.",
    publishedAt: "2026-08-10",
  },
  {
    id: "job-02",
    titleAr: "أخصائي استقطاب مواهب وموارد بشرية (Talent Acquisition)",
    titleEn: "Talent Acquisition Specialist",
    departmentId: "org-hr",
    departmentName: "الإدارة العامة للموارد البشرية",
    locationId: "loc-01",
    locationName: "المقر الرئيسي (الرياض)",
    employmentType: "full_time",
    openingsCount: 1,
    filledCount: 0,
    publishedStatus: "published",
    salaryMin: 14000,
    salaryMax: 18000,
    descriptionAr: "قيادة عمليات التوظيف والمقابلات واستقطاب الكفاءات التقنية والتنفيذية للشركة.",
    descriptionEn:
      "Lead talent acquisition and technical hiring pipelines across all subsidiaries.",
    requirementsAr: "خبرة سابقة في استقطاب الكفاءات التقنية بالسوق السعودي.",
    requirementsEn: "Strong sourcing background in Saudi technical talent market.",
    publishedAt: "2026-08-15",
  },
];

export const mockCandidates: Candidate[] = [
  {
    id: "cand-01",
    jobId: "job-01",
    jobTitle: "مطور واجهات ومصمم تجربة مستخدم",
    fullName: "ياسر العثمان",
    email: "yasser.othman@example.com",
    phone: "+966 50 111 2233",
    stage: "interview",
    ratingScore: 4.7,
    appliedDate: "2026-08-18",
    source: "linkedin",
    notesCount: 3,
  },
  {
    id: "cand-02",
    jobId: "job-01",
    jobTitle: "مطور واجهات ومصمم تجربة مستخدم",
    fullName: "هدى السالم",
    email: "huda.salem@example.com",
    phone: "+966 54 222 3344",
    stage: "assessment",
    ratingScore: 4.9,
    appliedDate: "2026-08-20",
    source: "website",
    notesCount: 4,
  },
  {
    id: "cand-03",
    jobId: "job-01",
    jobTitle: "مطور واجهات ومصمم تجربة مستخدم",
    fullName: "طارق الشهري",
    email: "tariq.shehri@example.com",
    phone: "+966 56 333 4455",
    stage: "job_offer",
    ratingScore: 5.0,
    appliedDate: "2026-08-12",
    source: "referral",
    notesCount: 6,
  },
  {
    id: "cand-04",
    jobId: "job-02",
    jobTitle: "أخصائي استقطاب مواهب",
    fullName: "سلطانة المنصور",
    email: "sultana.m@example.com",
    phone: "+966 59 444 5566",
    stage: "screening",
    ratingScore: 4.2,
    appliedDate: "2026-08-27",
    source: "linkedin",
    notesCount: 1,
  },
];

export const mockJobOffers: JobOffer[] = [
  {
    id: "offer-01",
    candidateId: "cand-03",
    candidateName: "طارق الشهري",
    jobTitle: "Senior Full-Stack UI Engineer",
    basicSalary: 17000,
    housingAllowance: 4250,
    transportAllowance: 1250,
    proposedStartDate: "2026-10-01",
    status: "sent_to_candidate",
  },
];

// ----------------------------------------------------------------------------
// M16: Hardware Assets & Company Documents
// ----------------------------------------------------------------------------
export const mockAssets: HardwareAsset[] = [
  {
    id: "ast-01",
    assetTag: "AST-MBP-0142",
    nameAr: "جهاز ماك بوك برو 16 إنش (M3 Max)",
    nameEn: 'MacBook Pro 16" (M3 Max, 36GB)',
    category: "laptop",
    serialNumber: "C02G89XYMD6T",
    assignedToEmployeeId: "emp-01",
    assignedToEmployeeName: "خالد المهيري",
    assignedDate: "2023-01-15",
    status: "assigned",
  },
  {
    id: "ast-02",
    assetTag: "AST-MBP-0188",
    nameAr: "جهاز ماك بوك برو 14 إنش (M3 Pro)",
    nameEn: 'MacBook Pro 14" (M3 Pro, 18GB)',
    category: "laptop",
    serialNumber: "C02H12KLMD7R",
    assignedToEmployeeId: "emp-05",
    assignedToEmployeeName: "محمد الشمري",
    assignedDate: "2023-02-10",
    status: "assigned",
  },
  {
    id: "ast-03",
    assetTag: "AST-KEY-0099",
    nameAr: "بطاقة دخول أمنية ذكية لمقر العليا",
    nameEn: "Olaya Tower Access Card",
    category: "security_card",
    serialNumber: "SEC-9988221",
    assignedToEmployeeId: "emp-07",
    assignedToEmployeeName: "ريم الدوسري",
    assignedDate: "2022-08-14",
    status: "assigned",
  },
  {
    id: "ast-04",
    assetTag: "AST-MBP-0220",
    nameAr: "جهاز ماك بوك أير 15 إنش (M3)",
    nameEn: 'MacBook Air 15" M3',
    category: "laptop",
    serialNumber: "C02J55FFMD88",
    status: "available",
  },
];

export const mockCompanyDocs: CompanyDocument[] = [
  {
    id: "doc-01",
    titleAr: "اللائحة الداخلية لتنظيم العمل وإجراءات السلامة 2026",
    titleEn: "Internal Work Organization & Safety Policy 2026",
    category: "regulation",
    version: "v3.2",
    fileUrl: "/docs/work-regulation-2026.pdf",
    visibilityScope: "all",
    requiresAcknowledgment: true,
    acknowledgedCount: 132,
  },
  {
    id: "doc-02",
    titleAr: "دليل سياسة العمل المرن والعمل عن بعد",
    titleEn: "Hybrid & Remote Work Operational Policy",
    category: "policy",
    version: "v2.0",
    fileUrl: "/docs/remote-work-policy.pdf",
    visibilityScope: "all",
    requiresAcknowledgment: true,
    acknowledgedCount: 128,
  },
  {
    id: "doc-03",
    titleAr: "سياسة النفقات والسفر والانتدابات الرسمية",
    titleEn: "Business Travel & Expense Guidelines",
    category: "policy",
    version: "v1.4",
    fileUrl: "/docs/travel-expense-policy.pdf",
    visibilityScope: "all",
    requiresAcknowledgment: false,
    acknowledgedCount: 95,
  },
];

// ----------------------------------------------------------------------------
// M17, M18, M19: Reports, Accounting Journals, Audit Trail & Notifications
// ----------------------------------------------------------------------------
export const mockAuditLogs: AuditLogEntry[] = [
  {
    id: "aud-01",
    actorId: "emp-04",
    actorName: "سارة العتيبي",
    actorRole: "مدير الموارد البشرية",
    action: "اعتماد سلفة مالية (Approval)",
    entityType: "LoanRecord",
    entityId: "loan-01",
    entityName: "مشعل الغامدي",
    timestamp: "2026-08-30T14:22:10Z",
    ipAddress: "192.168.1.45",
    changesSummary: "تم اعتماد سلفة بقيمة 6,000 ر.س مقسمة على 6 أقساط شهرية",
  },
  {
    id: "aud-02",
    actorId: "emp-02",
    actorName: "نورة القحطاني",
    actorRole: "مدير المالية والرواتب",
    action: "توليد مسير الرواتب الشهري (Payroll Run)",
    entityType: "PayrollRun",
    entityId: "pr-2026-08",
    entityName: "مسير أغسطس 2026",
    timestamp: "2026-08-30T11:15:40Z",
    ipAddress: "192.168.1.18",
    changesSummary: "تم احتساب المسير بنجاح لـ 120 موظف بإجمالي صافي 1,950,300 ر.س",
  },
  {
    id: "aud-03",
    actorId: "emp-01",
    actorName: "خالد المهيري",
    actorRole: "مدير مباشر",
    action: "اعتماد مطالبة مصروفات (Expense Approval)",
    entityType: "ExpenseClaim",
    entityId: "claim-01",
    entityName: "ريم الدوسري",
    timestamp: "2026-08-29T16:40:00Z",
    ipAddress: "192.168.1.10",
    changesSummary: "موافقة على مطالبة مصروف دورة الذكاء الاصطناعي بقيمة 3,850 ر.س",
  },
];

export const mockNotifications: AppNotification[] = [
  {
    id: "notif-01",
    recipientId: "emp-01",
    titleAr: "طلب إجازة جديد بانتظار موافقتك",
    titleEn: "New Leave Request Awaiting Approval",
    messageAr: "قدم محمد الشمري طلب إجازة سنوية لمدة 6 أيام تبدأ في 5 سبتمبر 2026.",
    messageEn:
      "Mohammed Al-Shammari submitted an annual leave request for 6 days starting Sep 5, 2026.",
    type: "leave",
    actionUrl: "/requests",
    isRead: false,
    createdAt: "2026-08-28T09:31:00Z",
  },
  {
    id: "notif-02",
    recipientId: "emp-02",
    titleAr: "مسير رواتب أغسطس 2026 جاهز للمراجعة",
    titleEn: "August 2026 Payroll Ready for Review",
    messageAr: "اكتملت معالجة الحضور والغيابات لمسير أغسطس وجاهز للاعتماد والقفل.",
    messageEn: "Attendance inputs processed. August payroll is ready for final review and locking.",
    type: "payroll",
    actionUrl: "/payroll",
    isRead: false,
    createdAt: "2026-08-30T11:20:00Z",
  },
  {
    id: "notif-03",
    recipientId: "emp-07",
    titleAr: "تمت الموافقة على مطالبة المصروفات",
    titleEn: "Expense Claim Approved",
    messageAr:
      "اعتمد المدير المباشر مطالبتك الخاصة بورشة عمل الذكاء الاصطناعي وتم تحويلها للمالية.",
    messageEn: "Your AI workshop claim was approved by direct manager and forwarded to finance.",
    type: "request",
    actionUrl: "/expenses",
    isRead: true,
    createdAt: "2026-08-27T11:05:00Z",
  },
];

export const mockAccountingJournals: AccountingJournalEntry[] = [
  {
    id: "jrn-2026-07",
    journalNo: "JV-2026-07-001",
    sourceType: "payroll_run",
    sourceReference: "pr-2026-07",
    date: "2026-07-28",
    totalDebit: 2273700,
    totalCredit: 2273700,
    status: "synced_to_erp",
    erpIntegrationType: "odoo",
  },
];
